// Generated by Melange

import * as Bindings__Image from "./bindings/Image.js";
import * as Bindings__Link from "./bindings/Link.js";
import * as JsxRuntime from "react/jsx-runtime";

function Page$default(Props) {
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("p", {
                              children: [
                                "Get started by editing",
                                JsxRuntime.jsx("code", {
                                      children: "src/app/page.tsx",
                                      className: "font-mono font-bold ml-2"
                                    })
                              ],
                              className: "fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("a", {
                                    children: [
                                      "By",
                                      JsxRuntime.jsx(Bindings__Image.make, {
                                            className: "dark:invert",
                                            src: "/vercel.svg",
                                            alt: "Vercel Logo",
                                            width: 100,
                                            height: 24,
                                            priority: true
                                          })
                                    ],
                                    className: "pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0",
                                    href: "https://vercel.com?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                                    rel: "noopener noreferrer",
                                    target: "_blank"
                                  }),
                              className: "fixed bottom-0 left-0 flex h-48 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none"
                            })
                      ],
                      className: "z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(Bindings__Image.make, {
                            className: "relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert",
                            src: "/next.svg",
                            alt: "Next.js Logo",
                            width: 180,
                            height: 37,
                            priority: true
                          }),
                      className: "relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        "Docs",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Find in-depth information about Next.js features and API.",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ],
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        "Learn",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Learn about Next.js in an interactive course with quizzes!",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ],
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        "Templates",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Explore the Next.js 13 playground.",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ],
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs("a", {
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        "Deploy",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Instantly deploy your Next.js site to a shareable URL with Vercel.",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ],
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app",
                              rel: "noopener noreferrer",
                              target: "_blank"
                            }),
                        JsxRuntime.jsxs(Bindings__Link.make, {
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "/dogs",
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        JsxRuntime.jsx("img", {
                                              className: "mr-1",
                                              alt: "Reason Logo",
                                              src: "/icon_50.png",
                                              width: "30"
                                            }),
                                        "Dogs",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "flex mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "View a dog picture",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(Bindings__Link.make, {
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "/jokes",
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        JsxRuntime.jsx("img", {
                                              className: "mr-1",
                                              alt: "Reason Logo",
                                              src: "/icon_50.png",
                                              width: "30"
                                            }),
                                        "Jokes",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "flex mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Read a joke",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs(Bindings__Link.make, {
                              className: "group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30",
                              href: "/rick-and-morty",
                              children: [
                                JsxRuntime.jsxs("h2", {
                                      children: [
                                        JsxRuntime.jsx("img", {
                                              className: "mr-1",
                                              alt: "Reason Logo",
                                              src: "/icon_50.png",
                                              width: "30"
                                            }),
                                        "Rick & Morty",
                                        JsxRuntime.jsx("span", {
                                              children: "\u2192",
                                              className: "inline-block ml-2 transition-transform group-hover:translate-x-1 motion-reduce:transform-none"
                                            })
                                      ],
                                      className: "flex mb-3 text-2xl font-semibold"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: "Rick & Morty characters",
                                      className: "m-0 max-w-[30ch] text-sm opacity-50"
                                    })
                              ]
                            })
                      ],
                      className: "mb-32 grid text-center lg:mb-0 lg:grid-cols-4 lg:text-left"
                    })
              ],
              className: "flex min-h-screen flex-col items-center justify-between p-24"
            });
}

var $$default = Page$default;

export {
  $$default as default,
}
/* Bindings__Image Not a pure module */
