// Generated by Melange

import * as JsxRuntime from "react/jsx-runtime";

import './globals.css'
;

import { Inter } from 'next/font/google'
;

const inter = Inter({ subsets: ['latin'], display: 'swap' })
;

function Layout$default(Props) {
  var children = Props.children;
  return JsxRuntime.jsx("html", {
              children: JsxRuntime.jsx("body", {
                    children: children,
                    className: inter.className
                  }),
              lang: "en"
            });
}

var $$default = Layout$default;

export {
  $$default as default,
}
/*  Not a pure module */
