// Generated by Melange

import * as Bindings__Link from "../bindings/Link.js";
import * as Json__Json_decode from "melange-json/Json_decode.js";
import * as Stdlib__Int from "melange/int.js";
import * as JsxRuntime from "react/jsx-runtime";

function decodeCharacter(json) {
  return {
          id: Json__Json_decode.field("id", Json__Json_decode.$$int, json),
          name: Json__Json_decode.field("name", Json__Json_decode.string, json)
        };
}

function decodeInfo(json) {
  return {
          count: Json__Json_decode.field("count", Json__Json_decode.$$int, json),
          pages: Json__Json_decode.field("pages", Json__Json_decode.$$int, json),
          next: Json__Json_decode.field("next", Json__Json_decode.string, json),
          prev: Json__Json_decode.field("prev", (function (param) {
                  return Json__Json_decode.optional(Json__Json_decode.string, param);
                }), json)
        };
}

function decodeCharactersResultsObject(json) {
  return {
          info: Json__Json_decode.field("info", decodeInfo, json),
          results: Json__Json_decode.field("results", (function (param) {
                  return Json__Json_decode.array(decodeCharacter, param);
                }), json)
        };
}

function PageComponent$default(Props) {
  var json = Props.json;
  var createLi = function (c) {
    var stringOfId = Stdlib__Int.to_string(c.id);
    return JsxRuntime.jsx("li", {
                children: JsxRuntime.jsx(Bindings__Link.make, {
                      className: "underline",
                      href: " /rick-and-morty/" + stringOfId + " ",
                      children: c.name
                    }),
                className: "p-4 hover:bg-slate-800 rounded-md"
              }, stringOfId);
  };
  var charactersList = function (json) {
    var data = decodeCharactersResultsObject(json);
    var lis = data.results.map(createLi);
    return JsxRuntime.jsx("ul", {
                children: lis
              });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                charactersList(json),
                JsxRuntime.jsx(Bindings__Link.make, {
                      className: "underline",
                      href: "/",
                      children: "back"
                    })
              ],
              className: "ml-4"
            });
}

var $$default = PageComponent$default;

export {
  $$default as default,
}
/* Bindings__Link Not a pure module */
