"use client";
// Generated by Melange

import * as Curry from "melange.js/curry.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Error$default(Props) {
  var error = Props.error;
  var reset = Props.reset;
  React.useEffect((function () {
          console.log("Error: ", error);
        }), [error]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Something went wrong!"
                    }),
                JsxRuntime.jsx("button", {
                      children: "Try again",
                      className: "p-2 mt-2 bg-blue-800",
                      onClick: (function (param) {
                          Curry._1(reset, undefined);
                        })
                    })
              ]
            });
}

var $$default = Error$default;

export {
  $$default as default,
}
/* react Not a pure module */
