// Generated by Melange

import * as JsxRuntime from "react/jsx-runtime";

function Loading$default(Props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            className: "rounded-full bg-slate-700 h-10 w-10"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    className: "h-2 bg-slate-700 rounded"
                                  }),
                              JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsxs("div", {
                                            children: [
                                              JsxRuntime.jsx("div", {
                                                    className: "h-2 bg-slate-700 rounded col-span-2"
                                                  }),
                                              JsxRuntime.jsx("div", {
                                                    className: "h-2 bg-slate-700 rounded col-span-1"
                                                  })
                                            ],
                                            className: "grid grid-cols-3 gap-4"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            className: "h-2 bg-slate-700 rounded"
                                          })
                                    ],
                                    className: "space-y-3"
                                  })
                            ],
                            className: "flex-1 space-y-6 py-1"
                          })
                    ],
                    className: "animate-pulse flex space-x-4"
                  }),
              className: "border border-blue-300 shadow rounded-md p-4 max-w-sm w-full"
            });
}

var $$default = Loading$default;

export {
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
