"use client";
// Generated by Melange

import * as Bindings__Image from "../../../reason_bindings/Image.js";
import * as Bindings__Link from "../../../reason_bindings/Link.js";
import * as Curry from "melange.js/curry.js";
import * as Json__Json_decode from "melange-json/Json_decode.js";
import * as $$Promise from "../../../node_modules/reason-promise/src/js/promise.js";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function decodeOrigin(json) {
  return {
          name: Json__Json_decode.field("name", Json__Json_decode.string, json),
          url: Json__Json_decode.field("url", Json__Json_decode.string, json)
        };
}

function decodeLocation(json) {
  return {
          name: Json__Json_decode.field("name", Json__Json_decode.string, json),
          url: Json__Json_decode.field("url", Json__Json_decode.string, json)
        };
}

function Page$default(Props) {
  var params = Props.params;
  var match = React.useState(function () {
        
      });
  var setCharacter = match[1];
  var character = match[0];
  React.useEffect((function () {
          $$Promise.get($$Promise.map($$Promise.flatMap(fetch("https://rickandmortyapi.com/api/character/" + params.id), (function (res) {
                          return res.json();
                        })), (function (json) {
                      return {
                              id: Json__Json_decode.field("id", Json__Json_decode.$$int, json),
                              name: Json__Json_decode.field("name", Json__Json_decode.string, json),
                              status: Json__Json_decode.field("status", Json__Json_decode.string, json),
                              species: Json__Json_decode.field("species", Json__Json_decode.string, json),
                              type_of_character: Json__Json_decode.field("type", Json__Json_decode.string, json),
                              gender: Json__Json_decode.field("gender", Json__Json_decode.string, json),
                              origin: Json__Json_decode.field("origin", decodeOrigin, json),
                              location: Json__Json_decode.field("location", decodeLocation, json),
                              image: Json__Json_decode.field("image", Json__Json_decode.string, json),
                              episode: Json__Json_decode.field("episode", (function (param) {
                                      return Json__Json_decode.array(Json__Json_decode.string, param);
                                    }), json),
                              url: Json__Json_decode.field("url", Json__Json_decode.string, json),
                              created: Json__Json_decode.field("created", Json__Json_decode.string, json)
                            };
                    })), (function (ch) {
                  Curry._1(setCharacter, (function (param) {
                          return ch;
                        }));
                }));
        }), []);
  var characterComponent = function (c) {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("h3", {
                        children: c.name
                      }),
                  JsxRuntime.jsx(Bindings__Image.make, {
                        src: c.image,
                        alt: c.name,
                        width: 500,
                        height: 500,
                        placeholder: "blur",
                        blurDataURL: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg=="
                      }),
                  JsxRuntime.jsx("p", {
                        children: "Status: " + c.status
                      })
                ]
              });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: character !== undefined ? characterComponent(character) : "Loading"
                    }),
                JsxRuntime.jsx(Bindings__Link.make, {
                      className: "underline",
                      href: "/rick-and-morty",
                      children: "back"
                    })
              ],
              className: "ml-4"
            });
}

var $$default = Page$default;

export {
  $$default as default,
}
/* Bindings__Image Not a pure module */
